# Generated by Django 4.1.3 on 2022-12-04 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='length',
            new_name='height',
        ),
    ]
